# -*- coding: utf-8 -*-
# 05.03.2019 Julia Müller
# revised by Anna Jäkel

finish_message = "--> All done! \n\nOutputfile: {0}\n\nVolume is: {1}\n"
error_message = "--> Please give me a parameter file!\n(Format should be parameterfiles/'name of parameterfile')\n"
info_message = ";FLAVOR:RepRap\n;TIME: {0}\n"\
        + ";Filament used: {1}" \
        + ";Layer height: {2}\n"\
        + ";Nozzle used: {3}\n"\
        + ";Generated by Julia's Generator\n"\
        + ";with the following parameterfile: {4}\n\n"
start_routine = "M107	; turn fan off" + "\n"\
        + "M302	;allow cold extrudes" + "\n"\
        + "G21 ;metric values\n"\
        + "G90 ;absolute positioning\n"\
        + "M83 ;set extruder to relative mode\n"\
        + "M92 E3200; 1 mm syringe pump way is reached after 3200 motor steps\n"\
        + "M117 Home all axes ;Put home message on LCD screen\n"\
        + "G90 ; use absolute positioning like always\n"\
        + "G28 X0 ;move X to min endstop\nG28 Y0 ;move Y to min endstop\n"\
        + "G28 Z0 ;move Z to min endstop, get nozzle to 0 now\n"\
        + "G1 Z5"\
        + "G1 X10 Y10 ;move away from spring\n"\
        + "G92 Z" + "{6} ;set homebed to zero\n"\
        + ";M117 Printing cool gelly stuff ;Put printing message on LCD screen\n"\
        + "G1 X10 Y10 E0.2; Extrude to make sure gel is in the nozzle\n"\
        + "G1 Z" + "{2}"\
        + "; move z-stage down to not crash to the sample holder\n\n"\
        + "G1 F5000 X" + "{3}" + " Y" + "{4}"
end_routine = ";END ROUTINE\n"\
        + "G1 F1000 Z" + "{0}"\
        + " ;move Z to min endstop\n"\
        + "M117 Nice print!\n"\
        + "G28 X0 ;move X to min endstop\nG28 Y0 ;move Y to min endstop\n"\
        + "M84; Stop the Stepper Motors\n"\
        + "; in total " + "{1}" + " microliters for E1 necessary\n"\
        + "; in total " + "{2}" + " microliters for E2 necessary"
smallstart = ";smallstart: \n"\
        + ";TIME_ELAPSED calculate that\n"\
        + "G1 F2000 Z" + "{0}"\
        + "; move z-stage down to not crash to the sample holder\n"\
        + "G1 F" + "{1}"\
        + " X" + "{2}" + " Y" + "{3}"\
        + "; move to start position without extrusion\n"\
        + "G1 F" + "{4}" + "\n\n"
